deployTarget: LOCAL

global:
  securityContexts:
    enabled: true
  postgresql:
    postgresqlPassword: "pachyderm"
    postgresqlPostgresPassword: "pachyderm"

pachd:
  image:
    tag: local
  clusterDeploymentID: dev
  logLevel: debug
  logFormat: json
  activateEnterprise: true
  enterpriseLicenseKey: ""
  activateAuth: true
  rootToken: "fa03ee2e5be041aba4a7b5e4ed3db814"
  localhostIssuer: "true"
  storage:
    backend: MINIO
    minio:
      bucket: "pachyderm-test"
      endpoint: "minio.default.svc.cluster.local:9000"
      id: "minioadmin"
      secret: "minioadmin"
      secure: "false"
      signature: ""

pachw:
  minReplicas: 0
  maxReplicas: 10

console:
  enabled: true

postgresql:
  enabled: true
  service:
    type: NodePort

proxy:
  host: "host.wsl.albs"
  # host: "localhost"
  service:
    type: NodePort
